apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAV3bAH9eNGYyRd0aQ4NxYXKlF381o63Cn9CXO58jBgLNbAvLtyKMZPUgA1j+z4MWI+SwuPScoXdSkIV9ot1gC0aSLuDKLbVMMbRCPV9t2I5jDU0zTaHtF+srHUhg5SMKIQ7MjLyLn0uZOsEROZrJg8rDXLZW/K963cWRg9Vc6l9+CrTUKezLmwi93+UxaN0jBRZuCY5G1yS2kmamNH2aFP9DaI3elABk6AISKjQ2HUim/DQVgaSlkQjbGXidr2vwVKdNAZJKCtEWTePbE0gMPpqMiNxumHASnvhyeohFdrBAnzI+4fTNrUd6zffMAv44+k7KN1MVxmSohYsuGSZo1YLT70CNlBJsaSshcd/axCWfPlVSF1aUHxMf9/v18jcdnM7PMOEgMx38KYXPWdnjDX3jUUrH8WgsluUq2pRGvWOfF9l3BM8W/yw2Lz5Esb4/0rPsRLjBvOuHsMt8A1hS/0Uv3aYdxbbg5w5sPPRIcr1x4KtKif/1EYuJQihYw5rR+PJMoiPPbYalqMAdpQB+TIpU1OajF2n6FbIz4jONPLYKlBXMJr7lBL8NcCUAY8Bx4Fbk+VyuwK3KAgGt+nWWJHqBSZRWgJQbFMqMuV77QFAVvjO2xuiYs4lzv2MgUies6sETpY8wLWbiUmvaJFblp+VDFWeoPv35mYcvlSoKg7WjWZxNQzZ0uxRu6Qq6KX9hZdGo8TYlimMTwQ4yiv+/UI+8km7umhTsXSZoeUMnWxml1FtN1SEp3vJ06f/H8mcca6PjFlRmckci+jLLmbmLm0g3fWkbj+aPuihWPyGeV8+laxXRFDNGAjXTb2IPY0WKnYowx0JXBRxcp7XUcWeoqFbR3kNsxaU2OsBwkwUf1Zdll6WTqpOrI0gymsr5US9tGW8NWhbpMF7/loGXR1oq1ovl/PUJGu6/lDhh2b5AkVVIZC9wJ4peyuPhbxDwEtiamaRJpHW7I0TyOVaiuvPiI14rW7bAc7oMBPLRgdhCr4gB+U/bLIFxRW7ErbMyyhRPV2uwT0ADKGm39ahrEnWjtbAGZalX/8qOWj4AsNxzdx+ZFHVxX8wAgZnVTGqlhDat9Mgy4eoCKu+IxDZacKtaFgzbdiFu3bmduUHhp3gzH0jDShdXsQn+SlrOQg/sMp9NmaLG9dd9QVuXlVvRIcj6/e+e+h7jRrX3da1OgYKdRDQ7pKX+jLVCNwOfS3Gz8XS2efb7T/XvyA8USLhtgNS6eVxLXEjqkpSFOIvWS5Y8gHVKeK3NvxRGzON+03QpZk/epGzbgL+a7lDkbCoME6wwsJuJ93YIcWdRH8mymLIsttdtGPy+oBbe3e8o21BOu4z3xdjTxLSHr/EoyGjM6p6Rtc5Vqy8dlIed4A0JoSe3MnxsaK8N71zjiqL8PudEfkJRqz7mA+B3auOR+QGAzB+QqZxR3zkaGIo8ADu/tuJ8vmTdq7I/c0sHFbzwLo5zHidcYh7wga9euHcVHBPtC4Vq++yExXCbRqmDrnFMljgT+k0qtTa2n4PLq9QwPNFw8fc4D5Cm064ac=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
