apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAYRpkmrWq5ec6gW76DkHXzt8qC5uxX3StenZ2z+Y1mv3puUKM1BPlXzRN5qIVS5uC6kgK7m1DtHYsoj0chi+Ho4ISb/v/vRtVxTZvgxC6B7Z2PhO8q5aX+o+lL6WsgtAEE0VtviRCcQwMsilxsxQJxrQrrr7dpKJMfzjJi5G2XvfIEPCbkoqHplFPoCjMEGj6DzL4ofhqmQ0TYUN0pvZH1qhp1o7pYoPNTQFAZyNo2JL5sjOYW+XCDj23G8rPqVydhk04nfHLRSaMk0F/9qX6F0PvO4dA36i/A4uTw9Pp8XwtC25V+mcl4IpRSaJCqEjoOaDIUEY+tkLq+93+oV7VRHvdXrNzLcGz1Nr8kTHi7JAVvJHLmidTv5xOhTNYpYoH349MBK6z7QZMGbR4+ZnOM89qtOGDp7nEWK7L2zukd10yT6hW1OGMbhKn+siwkKCKT8bSelZJbKh3v+BxvcIqyg66i03PgM6K1Ok19qQWy241IpGRaf67kCY1d8aTDykCx6hQLhVxEe7snrAKFzvskezdumUSNSJ9yU2iF/KAk+oI1MfywiRh9cMaURtwdcX3HnqkC27ZjL3OazjiHqbEi5CGiXtSP6O3S1NDHgdLyfjyiGDkNG2VX5WTb6a3NvAa1vItdAYrLt3Mp9ziIvkjLZS+SBwzwl6PnPaSaoQOvut9WzeFy4rEvAYR4bZVn6mRZXVbi+Bln3h/okP1f0H18OOqzdu0=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
