apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-python-devfile
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAz9ofy9zHFI9EaJok1NR8FB7qdLF1qjdBoOi9mZg2X8030wxqDasH0CXZRbX6mdeGqPDoLtnz+achlyg6eT3A9y//+VkYBqbzqHQRbGJtLRUvu++xynrpPzCbp0RT1tpi8ME0QuSxf6EDRekMSq51x5bNZTc/JWPFcIcsEG7Imvsrq3HxsJ1mUR4lZwMo8yHklVx7hpXUzYoeAO7AR4aSswYca9RmCLg/6OglPib8xV+U5A+ZxUo2t2dn7PzteWHb9SYrmGUQEAl+IDbRRJNL3bldQM+TSw8F484Hi4G4DnasFWqSSZO5IvTo5ecA7LuV5UUtzuBkY+FoFooCLqqYBPmwgjwzNEthikD24gN5hUt2p+6XoHvBg+JC0vwwMK1M4WiYj87xXuMEzdGrPnPv7BFncRHOulVNTFjmk+3lR7diNU12bL/sue3q70AgmNakPIik/BWHOej4UXttX6Ng7FtcSe0eJX1EWOfgJlhkG6f+fNQt/FBk6/4SP043t4o+259+xyM0KSrcE+VHVCwRvfYpWL5FzoBFjosSho/G1+nwUKDGDG7PpFVR2YLoLuiGb96KE5KpxLnuWK8Xn8caMd7zoJeqJR2RDXP9mR2aUUwyYx+oY60Za65j411Gvzn2xy+8K9gKpq1BQ2hqT4znTpW3yOpSq9G7SxclJb6cu9l1bND1H1YAzCCs8nKDE73/bpKhAvlKuc03qiasG0jpNyqcoWSY=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-python-devfile
      namespace: cicd
    type: Opaque
