resources:
- 100-deployment.yaml
- 200-service.yaml
- 300-route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: image-registry.openshift-image-registry.svc:5000/cicd/python-devfile
  newTag: main-d1b51ba32c680430c6804acdce4eafec8b0e782a
