apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/starnold-redhat/python-demo-gitops3.git?ref=HEAD
  creationTimestamp: null
  name: dev
spec: {}
status: {}
